name: Run Benchmarks

on:
  schedule: 
    - cron: "0 2 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ALSA
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libasound2-dev
    - name: Run benchmarks
      run: cargo bench
 